#! /bin/bash

### BEGIN INIT INFO
# Provides: adhocserver
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start adhocserver
# Description: Start adhocserver 
### END INIT INFO

DESC="Adhocserver"
NAME=adhocserver
#DAEMON=

do_start()
{
   echo "starting Adhocserver...";
   FINALPATH_EXECUTABLE;
}

do_stop()
{
   echo "stopping Adhocserver...";
   killall -9 AdhocServer;
}

do_status(){
	test=$(ps -e | grep Adhoc| wc -l );
	if [ $test -eq 0 ] ; then
		echo "adhocserver is not running.";
		exit 1;
	else 
		echo "adhocserver is running.";
		exit 0;
	fi

}

case "$1" in
   start)
     do_start
     ;;
   stop)
     do_stop
     ;;
   status)
    do_status
    ;;
esac

exit 0
