#! /bin/bash

#dest folder
final_path=/home/yunohost.adhocserver/

#install required packages
sudo apt-get update -qq
sudo apt-get install -y -qq make libsqlite3-dev 

#add user with custom home
sudo useradd adhocserver -d $final_path
sudo mkdir -p $final_path
sudo chown adhocserver:adhocserver -R $final_path
sudo chmod 750 -R $final_path

#copy file to dest folder
sudo cp ../src/* $final_path

#build binary
sudo make -C $final_path

#copy service file and set permissions
sudo cp ../service/adhocserver /etc/init.d/
sudo chmod 755 /etc/init.d/adhocserver
sudo chown root:root /etc/init.d/adhocserver
#copying and setting the adhoc launcher script
sudo cp ../service/AdhocLaunch.sh $final_path
sudo chown adhocserver:adhocserver $final_path/AdhocLaunch.sh
sudo chmod 750 $final_path/AdhocLaunch.sh

#replace in service file the path to the binary executed with
#our newly created user. this will disallow an attaker to ger root
#rights if he introduces on système by this script
sudo sed -i "s,FINALPATH_EXECUTABLE,su - adhocserver -c $final_path/AdhocLaunch.sh,g" /etc/init.d/adhocserver

#add adhocserver as yunohost service
sudo yunohost service add adhocserver

