#! /bin/bash

#remove user and its home
sudo deluser adhocserver --remove-home
#remove service file 
sudo rm -f /etc/init.d/adhocserver
#close port
sudo yunohost firewall disallow TCP 27312
#delete service
sudo yunohost service remove adhocserver
